<?php

namespace ZnTool\Generator\Domain\Scenarios\Generate;

use Zend\Code\Generator\MethodGenerator;
use Zend\Code\Generator\PropertyGenerator;
use ZnCore\Base\Interfaces\GetLabelsInterface;
use ZnCore\Base\Legacy\Yii\Helpers\Inflector;
use ZnCore\Contract\Rbac\Interfaces\GetRbacInheritanceInterface;
use ZnTool\Generator\Domain\Helpers\ClassHelper;

class PermissionEnumScenario extends BaseScenario
{

    public function typeName()
    {
        return 'PermissionEnum';
    }

    public function classDir()
    {
        return 'Enums\Rbac';
    }

    /*protected function getClassName(): string
    {
        $timeStr = date('Y_m_d_His');
        $className = "m_{$timeStr}_create_{$this->name}_table";
        return $className;
    }*/

    protected function getClassName(): string
    {
        return Inflector::camelize($this->buildDto->domainName) . parent::getClassName(); // TODO: Change the autogenerated stub
    }

    protected function crudOperaions(): array
    {
        return [
            'crud' => 'Полный доступ',
            'all' => 'Просмотр списка',
            'one' => 'Просмотр записи',
            'create' => 'Создание',
            'update' => 'Редактирование',
            'delete' => 'Удаление',
            'restore' => 'Восстановление',
        ];
    }

    protected function generateConst()
    {
        foreach ($this->crudOperaions() as $operationName => $description) {
            $constName = strtoupper($operationName);
            $prefix = Inflector::camelize($this->buildDto->domainName) . Inflector::camelize($this->buildDto->name);
            $const = new PropertyGenerator();
            $const->setConst(true);
            $const->setName($constName);
            $const->setDefaultValue('o' . $prefix . Inflector::camelize($operationName));
            $this->getClassGenerator()->addPropertyFromGenerator($const);
        }
    }

    protected function tab(int $repeat = 1): string
    {
        return str_repeat(' ', $repeat * 4);
    }

    protected function generateGetLabelsMethod()
    {
        $this->addInterface(GetLabelsInterface::class);

        $labels = '';
        foreach ($this->crudOperaions() as $operationName => $description) {
            $constName = strtoupper($operationName);
            $prefix = Inflector::camelize($this->buildDto->domainName) . Inflector::camelize($this->buildDto->name);
            $labels .= $this->tab(1) . "self::{$constName} => '{$prefix}. {$description}'," . PHP_EOL;
        }

        $methodBody = "return [
{$labels}];";
        $methodGenerator = new MethodGenerator;
        $methodGenerator->setName('getLabels');
        $methodGenerator->setBody($methodBody);
        $methodGenerator->setStatic(true);
        $this->getClassGenerator()->addMethodFromGenerator($methodGenerator);
    }

    protected function generateGetInheritance()
    {
        $this->addInterface(GetRbacInheritanceInterface::class);

        $labels = '';
        foreach ($this->crudOperaions() as $operationName => $description) {
            if ($operationName != 'crud') {
                $constName = strtoupper($operationName);
                $labels .= $this->tab(2) . "self::{$constName}," . PHP_EOL;
            }
        }
        $labels = trim($labels, PHP_EOL);

        $methodBody =
            "return [
    self::CRUD => [
{$labels}
    ],
];";

        $methodGenerator = new MethodGenerator;
        $methodGenerator->setName('getInheritance');
        $methodGenerator->setBody($methodBody);
        $methodGenerator->setStatic(true);
        $this->getClassGenerator()->addMethodFromGenerator($methodGenerator);
    }

    protected function createClass()
    {
        $className = $this->getClassName();
        $fullClassName = $this->getFullClassName();
        $fileGenerator = $this->getFileGenerator();
        $classGenerator = $this->getClassGenerator();
        $classGenerator->setName($className);

        $this->generateConst();
        $this->generateGetLabelsMethod();
        $this->generateGetInheritance();
        //$classGenerator->addMethodFromGenerator($methodGenerator);

        $fileGenerator->setNamespace($this->classNamespace());
        $fileGenerator->setClass($classGenerator);

        $phpCode = $this->generateFileCode($fileGenerator);

        ClassHelper::generateFile($this->getFullClassName(), $phpCode);
    }
}
